# Generated by Django 3.1.3 on 2020-11-14 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_group_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='event',
        ),
    ]
