# Generated by Django 3.1.3 on 2020-11-14 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_remove_group_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='about',
            field=models.TextField(default='Vision', max_length=300),
        ),
    ]
