# Generated by Django 3.1.3 on 2020-11-15 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_group_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='about',
            field=models.TextField(default='Vision'),
        ),
    ]
