# Generated by Django 3.2.7 on 2021-09-13 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0002_auto_20201115_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
